imports:
  - { resource: parameters.ini }
  - { resource: security.yml }

framework:
  translator:      { fallback: en }
  secret:          %secret%
  charset:         UTF-8
  router:          { resource: "%kernel.root_dir%/config/routing.yml" }
  form:            true
  csrf_protection: true
  validation:      { enable_annotations: true }
  templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
  session:
    default_locale: %locale%
    auto_start:     true

twig:
  debug:            %kernel.debug%
  strict_variables: %kernel.debug%
  form:
    resources: ['form_table_layout.html.twig']

assetic:
  debug:          %kernel.debug%
  use_controller: false
  filters:
    cssrewrite: ~
    yui_css:
      jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar"
    yui_js:
      jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.6.jar"
    cssrewrite: ~

doctrine:
  dbal:
    driver:   %database_driver%
    host:     %database_host%
    port:     %database_port%
    dbname:   %database_name%
    user:     %database_user%
    password: %database_password%
    charset:  UTF8
  
  orm:
    auto_generate_proxy_classes: %kernel.debug%
    auto_mapping: true
    mappings:
      StofDoctrineExtensionsBundle: false

swiftmailer:
  transport: mail

jms_security_extra:
  secure_controllers:  true
  secure_all_services: false

fos_user:
  db_driver: orm
  firewall_name: general
  user_class: WiTTIE\CoreBundle\Entity\User
  group:
    group_class: WiTTIE\CoreBundle\Entity\Group
  registration:
    confirmation:
      enabled: false

stof_doctrine_extensions:
  default_locale: en_US
  orm:
    default:
      sluggable: true
      timestampable: true
      tree: true

stfalcon_tinymce:
  theme:
      mode: "textareas"
      theme: "advanced"
      plugins: "fullscreen"
      theme_advanced_buttons1: "cut,copy,paste,pastetext,pasteword,|,outdent,indent,blockquote,|,bold,italic,underline,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,|,undo,redo,|,link,unlink"
      theme_advanced_buttons2: ""
      theme_advanced_buttons3: ""
      theme_advanced_toolbar_location: "top"
      theme_advanced_toolbar_align: "left"
      theme_advanced_statusbar_location: "bottom"
      theme_advanced_buttons1_add: "fullscreen"
      theme_advanced_resizing: true
