security:
  role_hierarchy:
    ROLE_ADMIN:       []
    ROLE_SUPER_ADMIN: [ROLE_ALLOWED_TO_SWITCH, ROLE_ADMIN]
  
  providers:
    fos_userbundle:
      id: fos_user.user_manager
  
  firewalls:
    open:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false
    
    general:
      pattern: ^/
      form_login:
        provider: fos_userbundle
      logout:       true
      anonymous:    true
  
  access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, role: ROLE_ADMIN }
  
  encoders:
    Symfony\Component\Security\Core\User\User:
      algorithm:        sha1
      iterations:       1
      encode_as_base64: false
