<?php

namespace WiTTIE\EditorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SlotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlotRepository extends EntityRepository
{
	public function findOneById($id, $options = array())
	{
		$options = array_merge(array('id' => $id), $options);
		return $this->getQuery($options)->getSingleResult();
	}
	
	public function getQuery($options = array())
	{
		$qb = $this->createQueryBuilder('s');
		
		$qb->leftJoin('s.page','p');
		$qb->addSelect('p');
		
		$qb->leftJoin('s.response','r');
		$qb->addSelect('r');
		
		$qb->leftJoin('s.user','u');
		$qb->addSelect('u');
		
		if(isset($options['id']))
			$qb->andWhere('s.id = :id')->setParameter('id', $options['id']);
		
		return $qb->getQuery();
	}
}