<?php

namespace WiTTIE\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseRepository extends EntityRepository
{
	public function findOneById($id, $options = array())
	{
		$options = array_merge(array('id' => $id), $options);
		return $this->getQuery($options)->getSingleResult();
	}
	
	public function getQuery($options = array())
	{
		$qb = $this->createQueryBuilder('r');
		
		$qb->leftJoin('r.page','p');
		$qb->addSelect('p');
		
		$qb->leftJoin('r.slots','s');
		$qb->addSelect('s');
		
		if(isset($options['id']))
			$qb->andWhere('r.id = :id')->setParameter('id', $options['id']);
		
		if(isset($options['page']))
			$qb->andWhere('r.page = :page')->setParameter('page', $options['page']);
		
		return $qb->getQuery();
	}
}